### ISSUE TITLE
SSR error `window is not defined` - UMD webpack module?

### ISSUE THREAD

**Issue by mattboon** [kenneth-gray/react-aria-accordion#5]
First up, great library you made here!
Worked exactly as I'd hoped and was super easy to customise with render props :)

One thing is preventing us from using it right now:

## Prerequisites

- `react-aria-accordion` version: 1.0.3
- `react` version: 16.8.6
- `node` version: 10.4.0
- `npm` (or `yarn`) version: 6.9.0

## Relevant code

```javascript
{ ReferenceError: window is not defined
    at Object.<anonymous> (/app/node_modules/react-aria-accordion/lib/index.js:1:326)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.MmW3 (/app/build/server/static/fZS6vf6z0LTmT7u7zYqnp/pages/faq.js:6539:18)
    at __webpack_require__ (/app/build/server/static/fZS6vf6z0LTmT7u7zYqnp/pages/faq.js:23:31) type: 'ReferenceError', '$error': '$error' }
```

## What you did

I am trying to use the library with Server Side Rendering (SSR) via NextJS (`9.0.2`)

## What happened

I get the above `window is not defined` error when hard-refreshing a page that contains my Accordion, or when running my build process

```
"build": "NODE_ENV=production next build",
```

## Problem description

The bundled `react-aria-accordion/lib/index.js` file contains a signature like so

```javascript
(window,function(e){
 ..
})
```

Therefore SSR will not work as `window` is not defined

## Suggested solution

I saw the webpack (`4.8.0`) build config here has the following

```javascript
output: {
  libraryTarget: 'umd'
}
```

And [found this webpack issue](https://github.com/webpack/webpack/issues/6784) which seems to describe our situation.

It seems like they [pushed a fix earlier this year](https://github.com/webpack/webpack/pull/8625) so that UMD modules now compile _without_ a signature using `window`

So to fix the issue in question, I think merely updating webpack and rebuilding / republishing the package _should_ work?

**Comment by kenneth-gray** [comment]
@mattboon I never saw this, I'm sorry I haven't kept up with this. Looks like @kojiwakayama has created a PR to fix this issue. Will take a look at the weekend.

**Comment by kenneth-gray** [comment]
I suspect you're using something else now, but I've asked for a couple of changes and then I think it's ready to be merged.

**Comment by kojiwakayama** [comment]
@kenneth-gray can you publish a new version on npm? :)
